# Generated by Django 3.1.3 on 2021-01-28 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0002_competition_sportsman'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('leader', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('club', models.CharField(max_length=50, verbose_name='Клуб')),
            ],
        ),
    ]
